### ISSUE TITLE
Depth limit exceeded when using decision node

### ISSUE THREAD

**Issue by raunakkathuria** [gorules/zen-go#18]
# Problem

I am getting the following error when using the decision node from another file

```
panic: {"nodeId":"b5d45e09-d633-4e30-a7e8-2fb9e1b02097","source":"Depth limit exceeded","type":"NodeError"}
```

![image](https://github.com/gorules/zen-go/assets/2534747/26cb314d-4768-4251-ad01-a3a92508e1e2)

# Steps to reproduce

- `git clone git@github.com:raunakkathuria/gorules-zen-go-test.git` (https://github.com/raunakkathuria/gorules-zen-go-test)
- `cd gorules-zen-go-test`
- `go run main.go`

**Comment by StewartHuang** [comment]
I encountered a similar issue.
I resolved my problem by switching method from `engine.Evaluate` to the `engine.EvaluateWithOpts` and manually setting `EvaluationOptions.MaxDepth` to 2. 
By the way, I believe this is a bug. 
In my opinion, the reason for this bug might be: In the [code,](https://github.com/gorules/zen-go/blob/5b18bc0e473154f98d90a07ad5f947a0c09b477e/engine.go#L60) the implementation of the `engine.Evaluate` method calls `engine.EvaluateWithOpts`, and passes `EvaluationOptions`, but does not explicitly specify the value of `EvaluationOptions.MaxDepth`, so the default value is set to 0, thus limiting the reference level during the execution of decision.

**Comment by raunakkathuria** [comment]
Thanks @StewartHuang. It worked. Here is the diff for reference if anyone stumble on the same

```
-   response, err := engine.Evaluate("signup/graph.json", map[string]any{"residence": "es", "account": "real"})
+ response, err := engine.EvaluateWithOpts("signup/graph.json", map[string]any{"residence": "es", "account": "real"}, zen.EvaluationOptions{
+         Trace:    true,
+         MaxDepth: 2,
+ })
+
```

**Comment by raunakkathuria** [comment]
Looks like different methods with different syntax. `Evaluate` process with no options, `EvaluateWithOpts` expects these options. I will close the issue as this needs to be better documented and not a functionality issue
